server {
    listen 80;
    listen [::]:80;
    server_name movim.example.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name movim.example.com;

    ssl_certificate /etc/letsencrypt/live/movim.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/movim.example.com/privkey.pem;

    root /var/www/movim/public;
    index index.php;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy same-origin always;

    location /picture {
        set $no_cache 0;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location / {
        set $no_cache 1;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 1800s;
        proxy_send_timeout 1800s;
        proxy_redirect off;
    }

    location ~ \.php$ {
        add_header X-Cache $upstream_cache_status always;
        fastcgi_ignore_headers "Cache-Control" "Expires" "Set-Cookie";
        fastcgi_cache nginx_cache;
        fastcgi_cache_valid any 7d;
        fastcgi_cache_bypass $no_cache;
        fastcgi_no_cache $no_cache;

        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }
}
